### PR TITLE
BUG-INTALIO-001252 Web Browser XSS Protection Not Enabled

### PR DESCRIPTION
**Pull request by StanleyShen**
add header for XXS Protection

### CODE REVIEW

**Comment by michaelnsj** [comment]
should it need to add the same header for https?

**Comment by StanleyShen** [comment]
yes, also added missing X-FRAME-OPTIONS

**Comment by StanleyShen** [comment]
I am wrong, the X-FRAME-OPTIONS is already there.

**Comment by StanleyShen** [comment]
Done, can be merged.

**Pull request merged**
