### PR TITLE
add more security options

### PR DESCRIPTION
**Pull request by StanleyShen**
add more security settings for:
1. HSTS
2. Forward secrecy

Added for FT-INTALIO-000096 so that it helps we get score A in SSL testing.

https://www.ssllabs.com/ssltest/analyze.html

### CODE REVIEW

**Comment by shao** [comment]
---------- Forwarded message ----------
From: Andy Zhou <zhou@intalio.com>
Date: Tue, May 12, 2015 at 7:33 AM
Subject: Re: Stanley Shen Added Comment to Feature FT-INTALIO-000096 Check nginx support for these 3 features
To: Shao Fang <shao@intalio.com>


Actually, I amn't sure the changes. But the syntax is OK.

**Comment by shao** [comment]
Do we need to merge into 3.5 as well?

**Comment by StanleyShen** [comment]
yes, we can add it to 3.5 since the syntax works too with nginx 0.8.54.

**Comment by shao** [comment]
OK - so there is nothing that requires nginx 1.1.18.

By the way, if we decide to do a new 3.5 VM/AMI, we will be including nginx 1.1.18, not 0.8.54.

**Comment by StanleyShen** [comment]
from research result, I can see they work too with nginx 1.1.18.
I will confirm this with a newly created 3.5 image later.

**Pull request merged**
